"""Add user activity composite indexes

Revision ID: 8126c7e38b42
Revises: 8b3c162fda22
Create Date: 2025-08-18 21:17:51.855403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8126c7e38b42'
down_revision = '8b3c162fda22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('idx_user_date', ['user_id', 'start_date'], unique=False)
        batch_op.create_index('idx_user_type', ['user_id', 'type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('idx_user_type')
        batch_op.drop_index('idx_user_date')

    # ### end Alembic commands ###
